### ISSUE TITLE
Error occurs while trying to browse data with submitted multiline text

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav-plugin-data-manager#2] opened 2015-09-15 10:39 UTC
This is form.md:

```

---
title: A page with a form
form:
    name: contactform
    fields:
        - name: name
          label: Name
          placeholder: Enter your name
          autofocus: on
          autocomplete: on
          type: text
          validate:
            required: true

        - name: email
          label: Email
          placeholder: Enter your email address
          type: text
          validate:
            rule: email
            required: true

        - name: message
          label: Message
          placeholder: Enter your message
          type: textarea
          validate:
            required: true

    buttons:
        - type: submit
          value: Submit

    process:
        - save:
            fileprefix: contact-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        - message: Thank you from your feedback!

---

# Nice contact form

{% include 'forms/form.html.twig' %}
```

There is no additional configuration of Data Manager and Form plugins.

If multiline message was submitted, then error occurs while trying to browse Contactform data:
![Error](https://cloud.githubusercontent.com/assets/8279974/9874330/2beed434-5bae-11e5-91bd-e33f8ce95013.png)

**Comment by flaviocopes** [comment] 2015-09-15 14:08
Thanks for reporting! Just recreated on my local form too

**Comment by flaviocopes** [comment] 2015-09-15 21:36
The problem is how we store data. I've done some edits to transform a multiline string (e.g. a textarea content) to a single line string with `<br>` tags. Still something left to sort out, but will be fixed soon.

**Comment by flaviocopes** [comment] 2015-09-16 12:12
Should be solved in the next Form, Data Manager and themes releases (changes involve those 3 elements). Which theme are you using?

Data generated wrongly will still generate errors (need to manually edit it to work), but new data entered will now work fine.

**Closed as completed by flaviocopes** 2015-09-16 12:12 UTC
Labels: bug

**Comment by vistamedia** [comment] 2016-06-08 07:32
Hi guys, any news on a fix for that? Or any idea on way to escape all newlines and linebreaks of the submitted textarea?... Cheers. Grav rocks!!!

**Comment by dimitrilongo** [comment] 2017-08-01 11:18
it seems the bug is still here, anybody have a workaround ?
