### ISSUE TITLE
Data Manager Overwrites Custom Admin Route

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-data-manager#6] opened 2015-10-16 11:53 UTC
Installed Data Manager Plugin in Admin Panel 0.6.2.
--> custom admin route gets overwritten to default mysite/admin.

**Comment by flaviocopes** [comment] 2015-10-16 12:24
What happens exactly, the links inside the Data Manager admin area point to /admin/[whatever] ?

**Comment by axel-rank** [comment] 2015-10-16 12:44
In admin.yaml standard admin route is: route: '/admin'.
I changed this route to :  route: '/myroute'
So if I'm logged in and then install data manager plugin the admin route gets reset to /admin.
And after install I get an error: 'page doesn't exist'. So I have to change back to my custom admin route upload admin.yaml via ftp and login again.
No admin route resets in other plugins. (featherlight, shortcodes)

**Comment by flaviocopes** [comment] 2015-10-16 13:52
Really strange! And I cannot replicate this problem. You install Data Manager through the admin interface?

**Comment by flaviocopes** [comment] 2015-10-16 13:53
You changed the admin route in the `user/config/plugins/admin.yaml` file?

**Comment by axel-rank** [comment] 2015-10-16 15:23
Data Manager installed through admin interface.
Changed the route in user/plugins/admin/admin.yaml

**Comment by flaviocopes** [comment] 2015-10-16 15:29
The yaml file in the plugins folder is the default configuration. You need to copy that to user/config/plugins/admin.yaml and edit that from there, otherwise when the Admin plugin is updated, it's overwritten. That's probably what happened.

**Comment by axel-rank** [comment] 2015-10-16 15:33
No, I just tried again. Same issue. Install of other plugins work in admin panel. They don't reset admin login path to default.

**Comment by flaviocopes** [comment] 2015-10-16 15:46
Confirmed this happens. Since Data Manager has Admin under its dependencies, I think it installs the latest version of it even if it's already installed. Investigating. But it overwrites the `user/plugins/admin/admin.yaml` file. You should edit `user/config/plugins/admin.yaml`.

**Comment by flaviocopes** [comment] 2015-12-24 20:02
Closing as not an issue of the plugin, but of Grav

**Closed as completed by flaviocopes** 2015-12-24 20:02 UTC
