### ISSUE TITLE
Store multiline in Yaml data file from a textarea form field

### ISSUE THREAD

**Issue by masetto** [getgrav/grav-plugin-data-manager#20] opened 2017-09-23 10:29 UTC
I have an error when I store a multiline from a textarea form field, because in Yaml data file the textarea field has stored without `>` or `|` and indentation for each row.
I suggest to modify line 6 of `forms/data.txt.twig` from:
```
{{- field.name ?? index }}: {{ string((value is iterable ? value|json_encode : value)) ~ "\r\n" }}
```
To:
```
{{- field.name ?? index }}: {{ string((value is iterable ? value|json_encode : ("\n" in value ? (">\r\n  " ~ value|replace({"\n": "\n  "})) : value))) ~ "\r\n" }}
```

Perhaps it is better to create a specific twig file to perform this.

**Comment by hughbris** [comment] 2017-11-07 06:35
Just found this here! [Reported it](https://github.com/getgrav/grav-plugin-form/issues/205) and [submitted a PR](https://github.com/getgrav/grav-plugin-form/pull/206) two days ago in form plugin repo.

Also seems a duplicate of old bug #2 here, which is closed for some reason.

**Closed as completed** 2022-01-08 19:25 UTC
